[package]
name = "azure-kms-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.28.1"

[dependencies.mongodb]
path = "../.."
features = ["in-use-encryption", "azure-kms"]
